# -*- coding: utf-8 -*-
"""Libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjzrC157nJa7dHurJDrK1J8alZvEE2E9
"""

!pip install datasets
!pip install evaluate
!pip install rouge_score
!pip install openpyxl
!pip install bert-score
!pip install zemberek-python